import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
async function moduleFrom(path){const js=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;return import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));}
const security=await moduleFrom('lib/request-security.ts');
assert.equal(security.sameOrigin(new Request('https://saku.example/api/ledger',{headers:{origin:'https://evil.example'}})),false);
assert.equal(security.sameOrigin(new Request('https://saku.example/api/ledger')),false);
assert.equal(security.sameOrigin(new Request('https://saku.example/api/ledger',{headers:{origin:'https://saku.example'}})),true);
const receipt=await moduleFrom('lib/receipt-validation.ts');
assert.equal(receipt.validReceipt(new TextEncoder().encode('%PDF-1.7'),'application/pdf'),true);
assert.equal(receipt.validReceipt(new TextEncoder().encode('<script>alert(1)</script>'),'application/pdf'),false);
assert.equal(receipt.validReceipt(new Uint8Array([137,80,78,71,13,10,26,10]),'image/png'),true);
assert.equal(receipt.validReceipt(new Uint8Array([137,80]),'image/png'),false);
assert.equal(receipt.validReceipt(new TextEncoder().encode('xxxx0000WEBP'),'image/webp'),false);
assert.equal(receipt.validReceipt(new Uint8Array(receipt.MAX_RECEIPT_SIZE+1),'image/jpeg'),false);
const ledger=await moduleFrom('lib/ledger.ts');
const trip={id:'x',name:'Trip',start:'2026-10-08',days:2,advances:[0,0],advanceGroups:[{id:'g',start:1,end:2,amount:1000000}],transactions:[{id:'a',day:1,amount:200000,source:'advance',settled:null},{id:'b',day:2,amount:100000,source:'personal',settled:'advance'},{id:'c',day:2,amount:50000,source:'personal',settled:null}]};
assert.equal(ledger.summary(trip).balance,700000);
assert.equal(ledger.summary(trip).after,650000);
assert.equal(ledger.budgetSummary(trip,2).balance,700000);
assert.equal(ledger.budgetScopes(trip).length,1);
console.log('13 checks passed: CSRF, receipt signatures/size, grouped CA and reimburse balances.');
