'use client';
import {useEffect,useState} from 'react';
import TeamPanel from './team-panel';
import AppearanceSettings from './appearance-settings';
import {appearance,appearanceVars} from '@/lib/appearance';
import {Settings,Wallet,Plus,ReceiptText,Check,History,Users,Download,ChevronRight,Plane,RefreshCw,Pencil,Trash2,Camera,Paperclip,CalendarDays,CheckCircle2,Undo2,LayoutGrid,FileBarChart,ArrowUpRight,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Drawer,DrawerContent,DrawerTitle,DrawerDescription} from '@/components/ui/drawer';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Skeleton} from '@/components/ui/skeleton';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Toaster,toast} from 'sonner';
import {groupFor,budgetLabel,budgetScopes,budgetSummary,summary,rupiah,dayDate,type Ledger,type Transaction,type Trip,type Receipt,emptyLedger} from '@/lib/ledger';
const options={method:[['cash','Cash / tunai'],['transfer','Transfer pribadi']],source:[['advance','Cash advance'],['personal','Uang pribadi']],category:['Transportasi','Makan & minum','Tiket & aktivitas','Akomodasi','Operasional','Lainnya'].map(x=>[x,x])};
function Pick({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:string[][];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{items.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
const freshTx=(day:number)=>({day,description:'',vendor:'',category:'Operasional',amount:'',method:'cash',source:'advance',note:'',receipts:[] as Receipt[],id:''});
export default function LedgerApp({user}:{user:string}){
const [mobile,setMobile]=useState(false),[refreshing,setRefreshing]=useState(false);
useEffect(()=>{const q=window.matchMedia('(max-width: 760px)');const update=()=>setMobile(q.matches);update();q.addEventListener('change',update);return()=>q.removeEventListener('change',update)},[]);
const Modal=mobile?Drawer:Dialog,ModalContent=mobile?DrawerContent:DialogContent,ModalTitle=mobile?DrawerTitle:DialogTitle,ModalDescription=mobile?DrawerDescription:DialogDescription;
const [ledger,setLedger]=useState<Ledger>(emptyLedger),[version,setVersion]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false);
const [groupForm,setGroupForm]=useState({start:'1',end:'2',amount:''});
const [deleteTarget,setDeleteTarget]=useState<{id:string;name:string}|null>(null),[deleteName,setDeleteName]=useState('');
const [tripId,setTripId]=useState(''),[day,setDay]=useState(1),[tab,setTab]=useState('daily'),[modal,setModal]=useState(''),[formError,setFormError]=useState('');
const [tripForm,setTripForm]=useState({name:'',start:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Makassar'}),days:'10'}),[amount,setAmount]=useState(''),[tx,setTx]=useState(freshTx(1)),[settleTx,setSettleTx]=useState<Transaction|null>(null),[settleSource,setSettleSource]=useState('advance'),[confirmation,setConfirmation]=useState<{action:string;id:string;source?:null;label:string}|null>(null);
const look=appearance(ledger.appearance),labels=look.labels;
useEffect(()=>{const root=document.documentElement;const vars=appearanceVars(appearance(ledger.appearance));for(const [k,v] of Object.entries(vars))root.style.setProperty(k,v);document.title=appearance(ledger.appearance).labels.appName||'Catatan keuangan';return()=>{for(const k of Object.keys(vars))root.style.removeProperty(k)}},[ledger.appearance]);
const trip=ledger.trips.find(x=>x.id===tripId)||ledger.trips[0];const total=trip?summary(trip):null;const daily=trip?budgetSummary(trip,day):null;const activeGroup=trip?groupFor(trip,day):undefined;
async function load(){setRefreshing(true);setError('');try{const r=await fetch('/api/ledger',{cache:'no-store'});const j:any=await r.json();if(!r.ok)throw Error(j.error);setLedger(j.data);setVersion(j.version);}catch(e){setError(e instanceof Error?e.message:'Tidak dapat memuat data.');}finally{setLoading(false);setRefreshing(false)}}
useEffect(()=>{load();fetch('/api/team',{method:'POST'}).catch(()=>{})},[]);
useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const ctrl=new AbortController();Promise.resolve(c.registerTool({name:'read_tour_finances',description:'Read saved tour cash advances, daily balances and reimburse totals.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:any)=>{if(input&&Object.keys(input).length)throw Error('No arguments expected');const r=await fetch('/api/ledger');if(!r.ok)throw Error('Unable to load');const j:any=await r.json();setLedger(j.data);setVersion(j.version);return j.data.trips.map((t:Trip)=>({name:t.name,totals:summary(t),cashAdvances:budgetScopes(t).map(g=>({days:budgetLabel(t,g.start),...budgetSummary(t,g.start)})),days:t.advances.map((_,i)=>({day:i+1,expense:summary(t,i+1).expense,cashAdvanceGroup:budgetLabel(t,i+1)}))}));}},{signal:ctrl.signal})).catch(()=>{});return()=>ctrl.abort()},[]);
function open(m:string){setFormError('');setModal(m)}
async function mutate(body:any){setBusy(true);setFormError('');try{const r=await fetch('/api/ledger',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,tripId:body.tripId??trip?.id,version})});const j:any=await r.json();if(!r.ok)throw Error(j.error||'Gagal menyimpan');setLedger(j.data);setVersion(j.version);if(body.action==='trip'){setTripId(j.data.trips.at(-1).id);setDay(1)}if(body.action==='delete-trip'){setTripId(j.data.trips[0]?.id||'');setDay(1);setTab('daily');setDeleteTarget(null);setDeleteName('')}setModal('');setConfirmation(null);toast.success(body.action==='delete-trip'?'Trip berhasil dihapus':'Perubahan tersimpan');return true;}catch(e){const msg=e instanceof Error?e.message:'Gagal menyimpan';setFormError(msg);toast.error(msg);return false}finally{setBusy(false)}}
async function upload(files:FileList|null){if(!files?.length)return;setUploading(true);setFormError('');try{const added:Receipt[]=[];for(const f of Array.from(files)){if(tx.receipts.length+added.length>=8)throw Error('Maksimal 8 struk per transaksi.');if(f.size>10*1024*1024)throw Error('Maksimal 10 MB per struk.');const form=new FormData();form.append('file',f);const r=await fetch('/api/receipts',{method:'POST',body:form});const j=await r.json();if(!r.ok)throw Error(j.error);added.push(j);setTx(p=>({...p,receipts:[...p.receipts,j]}))}}catch(e){setFormError(e instanceof Error?e.message:'Unggah gagal')}finally{setUploading(false)}}
function edit(t:Transaction){setTx({...t,amount:String(t.amount)});open('transaction')}
async function exportFile(kind:'xlsx'|'pdf'){if(!trip)return;setBusy(true);try{const {exportTrip}=await import('@/lib/export');await exportTrip(trip,ledger.audit,kind);toast.success('Laporan diunduh')}catch{toast.error('Laporan gagal dibuat. Coba lagi.')}finally{setBusy(false)}}
function transactionList(list:Transaction[]){return list.length?<div className="transactions">{list.map(t=><div className="transaction" key={t.id}><div className={'tx-icon '+(t.source==='personal'?'personal':'')}><ReceiptText size={20}/></div><div className="tx-main"><strong>{t.description}</strong><div className="metadata">{tab!=='daily'&&<span>Day {t.day} · </span>}{t.vendor||t.category} · {t.method==='cash'?'Cash':'Transfer'} · {t.source==='personal'?'Uang pribadi':'Cash advance'}</div>{t.note&&<p className="tx-note">{t.note}</p>}<div className="receipt-links">{t.receipts.length?t.receipts.map(r=><a key={r.id} href={'/api/receipts?id='+r.id} target="_blank" rel="noreferrer"><Paperclip size={13}/>{r.name}</a>):<span>Belum ada struk</span>}</div></div><div className="tx-value"><strong>{rupiah(t.amount)}</strong>{t.source==='personal'?<span className={'badge '+(t.settled?'paid':'pending')}>{t.settled?'Lunas · '+(t.settled==='advance'?'CA '+budgetLabel(trip!,t.day):'kantor'):'Perlu reimburse'}</span>:<span className="badge">Dari cash advance</span>}</div><div className="tx-actions">{t.source==='personal'&&!t.settled&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>{setSettleTx(t);setSettleSource('advance');open('settle')}}>Lunasi</Button>}{t.settled?<Button size="icon" variant="ghost" aria-label="Batalkan pelunasan" onClick={()=>setConfirmation({action:'settle',id:t.id,source:null,label:'Batalkan pelunasan '+t.description+'?'})}><Undo2 size={16}/></Button>:<><Button size="icon" variant="ghost" aria-label={'Edit '+t.description} onClick={()=>edit(t)}><Pencil size={16}/></Button><Button size="icon" variant="ghost" aria-label={'Hapus '+t.description} onClick={()=>setConfirmation({action:'delete',id:t.id,label:'Hapus transaksi '+t.description+'?'})}><Trash2 size={16}/></Button></>}</div></div>)}</div>:<Empty className="empty"><EmptyHeader><ReceiptText className="empty-icon"/><EmptyTitle>Belum ada transaksi</EmptyTitle><EmptyDescription>Catat pengeluaran pertama, lalu lampirkan struknya.</EmptyDescription></EmptyHeader><Button aria-label="Tambah transaksi" onClick={()=>{setTx(freshTx(day));open('transaction')}}><Plus size={16}/> {labels.addTransaction}</Button></Empty>}
return <><Toaster richColors position="top-center"/><header className="header"><a className="brand" href="/" aria-label="Beranda"><span className="brand-icon"><Wallet size={22}/></span><span>{labels.appName}</span></a><div className="header-right"><button className="team-button settings-button" aria-label="Pengaturan tampilan" onClick={()=>open('appearance')}><Settings size={18}/><span>Pengaturan</span></button><button aria-label="Akses tim" className="team-button" onClick={()=>open('team')}><Users size={18}/><span>{labels.team}</span></button><form action="/api/auth/logout" method="post"><button className="team-button" type="submit">Keluar</button></form><span className="avatar" title={user}>{user[0].toUpperCase()}</span></div></header>
<main><div className="page-heading"><div><p className="greeting">{labels.greeting}</p><h1>{tab==='daily'?labels.dailyTitle:tab==='reimburse'?labels.reimburseTitle:tab==='report'?labels.reportTitle:labels.historyTitle}</h1></div><Button className="new-trip-button" aria-label="Buat trip baru" onClick={()=>open('trip')}><Plus size={20}/><span>{labels.newTrip}</span></Button></div>
{error&&<div className="error-box" role="alert">{error}<Button variant="outline" onClick={load}>Muat ulang</Button></div>}
{loading?<div className="stats">{[1,2,3,4].map(n=><Skeleton key={n} className="h-36 rounded-2xl"/>)}</div>:!trip?<section className="welcome"><div className="welcome-icon"><Plane size={34}/></div><div className="eyebrow">SIAP UNTUK TRIP BERIKUTNYA</div><h2>{labels.welcome}</h2><p>Buat trip, masukkan cash advance setiap hari,<br/>lalu catat pengeluaran sambil jalan.</p><Button size="lg" onClick={()=>open('trip')}><Plus size={18}/> Buat trip pertama</Button><div className="welcome-features"><span><CalendarDays/>Saldo terpisah per hari</span><span><Camera/>Struk tersimpan</span><span><CheckCircle2/>Reimburse terpantau</span></div></section>:<>
<div className="trip-bar"><div className="trip-selector"><span className="mini-icon"><Plane size={20}/></span><div><span className="small-label">TRIP AKTIF</span><Pick value={trip.id} label="Pilih trip" onChange={v=>{setTripId(v);setDay(1)}} items={ledger.trips.map(x=>[x.id,x.name])}/></div></div><span className="trip-dates">{dayDate(trip,1)} – {dayDate(trip,trip.days)} <b>{trip.days} hari</b></span><div className="trip-actions"><Button variant="ghost" size="icon" aria-label="Perbarui data" disabled={busy||refreshing} onClick={load}><RefreshCw size={18} className={refreshing?'spin':''}/></Button><Button className="delete-trip-button" variant="ghost" aria-label={'Hapus trip '+trip.name} disabled={busy} onClick={()=>{setDeleteTarget({id:trip.id,name:trip.name});setDeleteName('');setFormError('')}}><Trash2 size={17}/><span>Hapus trip</span></Button></div></div>
<section className="finance-overview" aria-label="Ringkasan keuangan trip"><div className="wallet-card"><div className="wallet-top"><span><Wallet size={18}/> {labels.balance}</span><span className="wallet-currency">IDR</span></div><div className="wallet-amount"><span>Rp</span><strong className={total!.balance<0?'negative':''}>{rupiah(total!.balance).replace('Rp','')}</strong></div><p>Saldo aktual seluruh trip</p><div className="wallet-details"><div><span>{labels.totalAdvance}</span><b>{rupiah(total!.advance)}</b></div><div><span>Terpakai dari CA</span><b>{rupiah(total!.advance-total!.balance)}</b></div></div></div><div className="metric-card"><span className="metric-icon blue"><ArrowUpRight size={21}/></span><span>{labels.totalExpense}</span><strong>{rupiah(total!.expense)}</strong><small>{trip.transactions.length} transaksi tercatat</small></div><button className="metric-card reimburse-card" onClick={()=>setTab('reimburse')}><span className="metric-icon orange"><History size={21}/></span><span>{labels.pending}</span><strong>{rupiah(total!.pending)}</strong><small>Lihat rincian <ChevronRight size={14}/></small></button></section>
<Tabs value={tab} onValueChange={v=>{setTab(v);if(mobile)window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}}><div className="tab-bar"><TabsList aria-label="Navigasi utama"><TabsTrigger value="daily" aria-label="Harian"><LayoutGrid/><span>{labels.dailyTab}</span></TabsTrigger><TabsTrigger value="reimburse" aria-label="Reimburse"><Wallet/><span>{labels.reimburseTitle}</span></TabsTrigger><TabsTrigger value="report" aria-label="Laporan"><FileBarChart/><span>{labels.reportTab}</span></TabsTrigger><TabsTrigger value="history" aria-label="Aktivitas"><History/><span>{labels.historyTitle}</span></TabsTrigger></TabsList><span className="currency">IDR · Rupiah</span></div>
<TabsContent value="daily"><div className="days-heading"><h2>Pilih hari</h2><Button variant="outline" disabled={busy||trip.days<2} onClick={()=>{setGroupForm({start:String(Math.min(day,trip.days-1)),end:String(Math.min(day+1,trip.days)),amount:''});open('group')}}><CalendarDays size={16}/>Gabungkan hari &amp; CA</Button></div><div className="days" aria-label="Pilih hari">{trip.advances.map((a,i)=>{const s=budgetSummary(trip,i+1);const g=groupFor(trip,i+1);return <button key={i} className={'day-card '+(day===i+1?'selected':'')} aria-pressed={day===i+1} onClick={e=>{setDay(i+1);e.currentTarget.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest',inline:'nearest'})}}><span>DAY {String(i+1).padStart(2,'0')} {day===i+1&&<span className="day-dot"/>}</span><strong>{rupiah(s.advance)}</strong><small>{g?budgetLabel(trip,i+1)+' · bersama':'CA harian'}</small><small>Sisa {rupiah(s.balance)}</small></button>})}</div><div className="daily-layout" key={trip.id+':'+day}><section className="panel transactions-panel"><div className="section-heading"><div><div className="eyebrow">{dayDate(trip,day)}</div><h2>Pengeluaran Day {day}</h2></div><Button aria-label="Tambah transaksi" onClick={()=>{setTx(freshTx(day));open('transaction')}}><Plus size={17}/><span>{labels.addTransaction}</span></Button></div>{transactionList(trip.transactions.filter(t=>t.day===day))}</section><aside className="panel balance-panel"><div className="section-heading"><h3>Ringkasan {budgetLabel(trip,day)}</h3><button className="icon-button" aria-label="Edit cash advance" onClick={()=>{setAmount(String(daily!.advance));open('advance')}}><Pencil size={17}/></button></div><div className="daily-advance"><span>Cash advance {budgetLabel(trip!,day)}</span><strong>{rupiah(daily!.advance)}</strong><button onClick={()=>{setAmount(String(daily!.advance));open('advance')}}>{daily!.advance?'Ubah nominal':'Masukkan cash advance'}</button></div><dl><div><dt>Pengeluaran dari CA</dt><dd>− {rupiah(daily!.direct)}</dd></div><div><dt>Reimburse dari CA</dt><dd>− {rupiah(daily!.fromAdvance)}</dd></div><div className="balance-total"><dt>Sisa aktual</dt><dd className={daily!.balance<0?'negative':''}>{rupiah(daily!.balance)}</dd></div></dl><div className="pending-box"><span>{labels.pending}</span><strong>{rupiah(daily!.pending)}</strong></div><p className="balance-note">Jika seluruh tagihan dibayar dari CA {budgetLabel(trip,day)}, sisa dana menjadi <b>{rupiah(daily!.after)}</b>.</p><div className="separate-note"><CheckCircle2 size={16}/><span>{activeGroup?'Saldo bersama untuk '+budgetLabel(trip,day)+'.':'Saldo tidak diteruskan ke hari berikutnya.'}</span></div>{activeGroup&&<Button variant="outline" className="ungroup-button" onClick={()=>open('ungroup')}>Pisahkan hari &amp; CA</Button>}</aside></div></TabsContent>
<TabsContent value="reimburse"><section className="panel"><div className="section-heading"><div className="eyebrow">UANG PRIBADI</div><h2>Reimburse seluruh trip</h2></div><div className="reimburse-totals"><span>Belum dibayar <b>{rupiah(total!.pending)}</b></span><span>Sudah dibayar <b>{rupiah(total!.reimbursed)}</b></span></div>{transactionList(trip.transactions.filter(t=>t.source==='personal'))}</section></TabsContent>
<TabsContent value="report"><section className="panel"><div className="section-heading"><div><div className="eyebrow">REKAP SELURUH PERJALANAN</div><h2>Laporan {trip.name}</h2></div><div className="export-buttons"><Button variant="outline" disabled={busy} onClick={()=>exportFile('xlsx')}><Download size={16}/> Excel</Button><Button disabled={busy} onClick={()=>exportFile('pdf')}><Download size={16}/> PDF</Button></div></div><Table><TableHeader><TableRow>{['Hari','Cash advance','Pengeluaran','Sisa aktual','Belum reimburse'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{budgetScopes(trip).map(g=>{const s=budgetSummary(trip,g.start);return <TableRow key={g.id}><TableCell><b>{budgetLabel(trip,g.start)}</b><small className="block muted">{dayDate(trip,g.start)}{g.end!==g.start?' – '+dayDate(trip,g.end):''}</small></TableCell>{[s.advance,s.expense,s.balance,s.pending].map((v,j)=><TableCell key={j} className={v<0?'negative':''}>{rupiah(v)}</TableCell>)}</TableRow>})}<TableRow className="total-row"><TableCell>Total</TableCell>{[total!.advance,total!.expense,total!.balance,total!.pending].map((v,i)=><TableCell key={i}>{rupiah(v)}</TableCell>)}</TableRow></TableBody></Table><div className="report-note">Sisa cash advance aktual: <b>{rupiah(total!.balance)}</b>. Jika seluruh reimburse tertunda dibayar dari CA, sisa dana: <b>{rupiah(total!.after)}</b>. Nilai negatif berarti kekurangan dana. Reimburse dari kantor: <b>{rupiah(total!.fromOffice)}</b>.</div></section></TabsContent>
<TabsContent value="history"><section className="panel"><div className="section-heading"><div><div className="eyebrow">JEJAK PERUBAHAN</div><h2>Riwayat aktivitas</h2></div><History/></div>{ledger.audit.filter(a=>a.tripId===trip.id||a.tripId==='settings').map(a=><div className="audit" key={a.id}><span className="audit-icon"><History size={17}/></span><div><strong>{a.action}</strong><p>{a.actor} · {new Date(a.at).toLocaleString('id-ID',{timeZone:'Asia/Makassar'})} WITA</p><details><summary>Lihat rincian perubahan</summary><pre>{a.detail}</pre></details></div></div>)}</section></TabsContent>
</Tabs></>}
<footer><span>{labels.appName}</span><span>Rupiah · WITA</span></footer></main>
<Modal open={!!modal} onOpenChange={v=>{if(!v&&!busy&&!uploading)setModal('')}}><ModalContent className="app-dialog">{mobile&&<button className="sheet-close" aria-label="Tutup formulir" disabled={busy||uploading} onClick={()=>setModal('')}><X size={18}/></button>}<ModalTitle><span className="sr-only">{modal==='team'?'Akses tim':modal==='transaction'?'Transaksi':''}</span>{({trip:'Buat trip baru',group:'Gabungkan hari & CA',ungroup:'Pisahkan hari & CA',advance:`Cash advance ${trip?budgetLabel(trip,day):''}`,transaction:tx.id?'Edit transaksi':labels.addTransaction,settle:'Lunasi reimburse',appearance:'Pengaturan tampilan',team:labels.team})[modal]}</ModalTitle><ModalDescription>{modal==='appearance'?'Sesuaikan tampilan aplikasi sesuai kebutuhanmu.':modal==='team'?'Lihat siapa yang membuka aplikasi dan mengubah catatan.':modal==='settle'?'Pelunasan penuh, tanpa mencatat biaya dua kali.':'Semua nominal dicatat dalam rupiah.'}</ModalDescription>
{formError&&<div className="error-box" role="alert">{formError}<Button variant="outline" size="sm" onClick={load}>Muat data terbaru</Button></div>}
{modal==='trip'&&<form onSubmit={e=>{e.preventDefault();mutate({action:'trip',...tripForm,days:Number(tripForm.days)})}}><label>Nama trip / grup<input required maxLength={200} placeholder="Contoh: Mexico Group — Bali" value={tripForm.name} onChange={e=>setTripForm({...tripForm,name:e.target.value})}/></label><div className="form-row"><label>Tanggal mulai<input required type="date" value={tripForm.start} onChange={e=>setTripForm({...tripForm,start:e.target.value})}/></label><label>Jumlah hari<input inputMode="numeric" required type="number" min="1" max="90" value={tripForm.days} onChange={e=>setTripForm({...tripForm,days:e.target.value})}/></label></div><p className="form-help">Cash advance dapat diisi dengan nominal berbeda untuk setiap hari.</p><Button disabled={busy} type="submit">{busy?'Menyimpan…':'Buat trip'}</Button></form>}
{modal==='advance'&&<form onSubmit={e=>{e.preventDefault();mutate({action:'advance',day,amount:Number(amount)})}}><label>Jumlah cash advance (Rp)<input inputMode="numeric" required type="number" min="0" max="100000000000" step="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="3500000"/></label><p className="form-help">{rupiah(Number(amount)||0)} · Alokasi untuk {trip?budgetLabel(trip,day):''}{activeGroup?' dengan satu saldo bersama':''}.</p><Button type="submit" disabled={busy}>Simpan cash advance</Button></form>}
{modal==='group'&&trip&&<form onSubmit={e=>{e.preventDefault();mutate({action:'group-advance',start:Number(groupForm.start),end:Number(groupForm.end),amount:Number(groupForm.amount)})}}><div className="form-row"><label>Dari hari<Pick label="Hari awal" value={groupForm.start} onChange={v=>setGroupForm({...groupForm,start:v})} items={trip.advances.map((_,i)=>[String(i+1),'Day '+(i+1)])}/></label><label>Sampai hari<Pick label="Hari akhir" value={groupForm.end} onChange={v=>setGroupForm({...groupForm,end:v})} items={trip.advances.map((_,i)=>[String(i+1),'Day '+(i+1)])}/></label></div><label>Satu nominal CA bersama (Rp)<input required type="number" inputMode="numeric" min="0" max="100000000000" step="1" placeholder="1600000" value={groupForm.amount} onChange={e=>setGroupForm({...groupForm,amount:e.target.value})}/></label><p className="form-help accent-help">{rupiah(Number(groupForm.amount)||0)} untuk Day {groupForm.start}–{groupForm.end}. Nominal ini menggantikan CA harian yang dipilih, bukan ditambahkan. Transaksi dan struk tetap pada hari asal.</p>{Number(groupForm.end)<=Number(groupForm.start)&&<p role="alert">Pilih minimal dua hari berurutan.</p>}{(trip.advanceGroups||[]).some(g=>Number(groupForm.start)<=g.end&&Number(groupForm.end)>=g.start)&&<p role="alert">Rentang ini memuat hari yang sudah tergabung. Pisahkan dahulu sebelum menggabungkan ulang.</p>}<Button disabled={busy||Number(groupForm.end)<=Number(groupForm.start)||(trip.advanceGroups||[]).some(g=>Number(groupForm.start)<=g.end&&Number(groupForm.end)>=g.start)} type="submit">Gabungkan hari &amp; simpan CA</Button></form>}
{modal==='ungroup'&&activeGroup&&<form onSubmit={e=>{e.preventDefault();mutate({action:'ungroup-advance',groupId:activeGroup.id})}}><p>Day {activeGroup.start}–{activeGroup.end} akan kembali terpisah. CA {rupiah(activeGroup.amount)} ditempatkan seluruhnya di Day {activeGroup.start}; hari lainnya Rp0. Setelah itu kamu bisa mengubah CA setiap hari atau menggabungkan ulang.</p><p className="form-help">Transaksi, reimburse, dan struk tetap pada hari asal. Total CA trip tetap sama.</p><Button type="submit" disabled={busy}>Pisahkan hari &amp; CA</Button></form>}
{modal==='transaction'&&trip&&<form onSubmit={e=>{e.preventDefault();mutate({action:'transaction',transaction:{...tx,id:tx.id||undefined,amount:Number(tx.amount)}})}}><div className="form-row"><label>Hari<Pick label="Hari transaksi" value={String(tx.day)} onChange={v=>setTx({...tx,day:Number(v)})} items={trip.advances.map((_,i)=>[String(i+1),'Day '+(i+1)])}/></label><label>Nominal (Rp)<input inputMode="numeric" required type="number" min="1" max="100000000000" step="1" value={tx.amount} onChange={e=>setTx({...tx,amount:e.target.value})} placeholder="500000"/></label></div><label>{labels.description}<input aria-label="Keperluan" required maxLength={200} value={tx.description} onChange={e=>setTx({...tx,description:e.target.value})} placeholder="Contoh: Makan siang grup"/></label><div className="form-row"><label>{labels.name}<input aria-label="Nama" maxLength={200} value={tx.vendor} onChange={e=>setTx({...tx,vendor:e.target.value})} placeholder="Masukkan nama"/></label><label>{labels.category}<Pick label="Kategori" value={tx.category} onChange={v=>setTx({...tx,category:v})} items={options.category}/></label></div><div className="form-row"><label>Cara pembayaran<Pick label="Cara pembayaran" value={tx.method} items={options.method} onChange={v=>setTx({...tx,method:v,source:v==='transfer'?'personal':tx.source})}/></label><label>Sumber dana<Pick label="Sumber dana" value={tx.source} items={tx.method==='transfer'?[['personal','Uang pribadi']]:options.source} onChange={v=>setTx({...tx,source:v})}/></label></div>{tx.source==='personal'&&<p className="form-help accent-help">Dicatat sebagai belum direimburse. Pelunasan dari CA akan memakai saldo {budgetLabel(trip,tx.day)}.</p>}<label>{labels.note}<textarea aria-label="Catatan" maxLength={2000} value={tx.note} onChange={e=>setTx({...tx,note:e.target.value})} placeholder="Keterangan tambahan (opsional)" rows={2}/></label><div className="upload-box"><strong><ReceiptText size={18}/> Struk pembayaran</strong><p>JPG, PNG, WebP atau PDF · maks. 10 MB per file</p><div className="upload-actions"><label className="upload-button"><Paperclip size={16}/> Unggah file<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" multiple disabled={uploading||busy} onChange={e=>upload(e.target.files)}/></label><label className="upload-button"><Camera size={16}/> Kamera<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" disabled={uploading||busy} onChange={e=>upload(e.target.files)}/></label></div>{uploading&&<p>Mengunggah…</p>}{tx.receipts.map(r=><div key={r.id} className="attached"><span>{r.name}</span><button type="button" aria-label={'Lepaskan '+r.name} onClick={()=>setTx({...tx,receipts:tx.receipts.filter(x=>x.id!==r.id)})}>×</button></div>)}</div><Button aria-label="Simpan transaksi" type="submit" disabled={busy||uploading}>{busy?'Menyimpan…':labels.saveTransaction||<Check size={20}/>}</Button></form>}
{modal==='settle'&&settleTx&&<form onSubmit={e=>{e.preventDefault();mutate({action:'settle',id:settleTx.id,source:settleSource})}}><div className="settle-summary"><span>{settleTx.description} · Day {settleTx.day}</span><strong>{rupiah(settleTx.amount)}</strong></div><label>Sumber pelunasan<Pick label="Sumber pelunasan" value={settleSource} onChange={setSettleSource} items={[["advance",'Cash advance '+(trip?budgetLabel(trip,settleTx.day):'')],['office','Transfer kantor langsung']]}/></label><p className="form-help">{settleSource==='advance'?'Saldo '+(trip?budgetLabel(trip,settleTx.day):'')+' akan berkurang '+rupiah(settleTx.amount)+'.':'Saldo cash advance tidak berkurang.'}</p><Button disabled={busy} type="submit"><Check size={17}/> Tandai sudah direimburse</Button></form>}
{modal==='appearance'&&<AppearanceSettings value={ledger.appearance} busy={busy} onSave={v=>mutate({action:'appearance',appearance:v})}/>}
{modal==='team'&&<TeamPanel audit={ledger.audit}/>}
</ModalContent></Modal>
<AlertDialog open={!!deleteTarget} onOpenChange={v=>{if(!v&&!busy){setDeleteTarget(null);setDeleteName('');setFormError('')}}}><AlertDialogContent className="delete-trip-dialog"><AlertDialogTitle>Hapus trip ini?</AlertDialogTitle><AlertDialogDescription>Trip <strong>{deleteTarget?.name}</strong> beserta cash advance, transaksi, dan catatan reimburse akan dihapus dari daftar aktif. Tindakan ini berlaku untuk seluruh tim dan tidak dapat dibatalkan dari aplikasi.</AlertDialogDescription><label className="delete-trip-label" htmlFor="delete-trip-name">Ketik nama trip untuk mengonfirmasi<input id="delete-trip-name" autoComplete="off" spellCheck={false} value={deleteName} onChange={e=>setDeleteName(e.target.value)} placeholder={deleteTarget?.name} disabled={busy}/></label>{formError&&<div className="error-box" role="alert">{formError}<Button variant="outline" disabled={busy||refreshing} onClick={load}>Muat data terbaru</Button></div>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Batal</AlertDialogCancel><AlertDialogAction className="confirm-delete-trip" disabled={busy||!deleteTarget||deleteName!==deleteTarget.name} onClick={e=>{e.preventDefault();if(deleteTarget)mutate({action:'delete-trip',tripId:deleteTarget.id,confirmName:deleteName})}}>{busy?'Menghapus…':'Hapus trip'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
<AlertDialog open={!!confirmation} onOpenChange={v=>{if(!v&&!busy)setConfirmation(null)}}><AlertDialogContent><AlertDialogTitle>{confirmation?.label}</AlertDialogTitle><AlertDialogDescription>Saldo akan dihitung ulang. Tindakan ini tetap tersimpan dalam riwayat perubahan.</AlertDialogDescription>{formError&&<p role="alert" className="negative">{formError}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Batal</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();if(confirmation)mutate(confirmation)}}>Ya, lanjutkan</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
</>;
}
