import {type Trip,type Audit,type Transaction,budgetScopes,budgetSummary,budgetLabel,groupFor,summary,dayDate,rupiah} from './ledger';
const stamp=(s:string)=>new Date(s).toLocaleString('id-ID',{timeZone:'Asia/Makassar'})+' WITA';
const status=(x:Transaction)=>x.source==='advance'?'Tidak perlu':x.settled?'Lunas':'Belum dibayar';
const paidFrom=(x:Transaction)=>x.settled==='advance'?'Cash advance':x.settled==='office'?'Kantor':'-';
const method=(x:Transaction)=>x.method==='cash'?'Cash / tunai':'Transfer';
const source=(x:Transaction)=>x.source==='advance'?'Cash advance':'Uang pribadi';
const link=(id:string,origin:string)=>new URL('/api/receipts?id='+id,origin).href;
export function auditDetail(raw:string){try{const j=JSON.parse(raw);const desc=(v:any)=>v?`Day ${v.day} | ${v.description} | ${rupiah(v.amount)} | ${v.method} | ${v.source==='advance'?'Cash advance':'Uang pribadi'} | Nama: ${v.vendor||'-'} | Kategori: ${v.category||'-'} | Catatan: ${v.note||'-'} | Struk: ${(v.receipts||[]).map((r:any)=>r.name).join(', ')||'-'}`:'Tidak ada';return 'after' in j?'Sebelum: '+desc(j.before)+'\nSesudah: '+desc(j.after):desc(j);}catch{return raw;}}
type Cell=string|number|{value:number;formula:string}|{text:string;url:string};
const col=(i:number)=>{let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s;};
const xml=(s:unknown)=>String(s).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
export async function createWorkbook(t:Trip,audit:Audit[],origin:string,template:Uint8Array){
const {unzipSync,zipSync,strFromU8,strToU8}=await import('fflate');const zip=unzipSync(template);const seed=strFromU8(zip['xl/worksheets/sheet1.xml']);
const styles=Array.from({length:11},(_,i)=>seed.match(new RegExp('<(?:[A-Za-z]+:)?c\\b[^>]*\\br="A'+(i+1)+'"[^>]*>'))?.[0].match(/\bs="(\d+)"/)?.[1]||'0');
const [title,subtitle,header,body,band,money,moneyBand,total,totalMoney,hyper,pending]=styles;
const last=6+Math.max(t.transactions.length,1);
const scopes=budgetScopes(t);
const daily:Cell[][]=scopes.map((g,i)=>{const s=budgetSummary(t,g.start),r=i+7;const sum=(extra='')=>Array.from({length:g.end-g.start+1},(_,j)=>`SUMIFS(Transaksi!$H$7:$H$${last},Transaksi!$A$7:$A$${last},"Day ${g.start+j}"${extra})`).join('+');return [budgetLabel(t,g.start),dayDate(t,g.start)+(g.end!==g.start?' - '+dayDate(t,g.end):''),s.advance,{value:s.expense,formula:sum()},{value:s.direct,formula:sum(`,Transaksi!$G$7:$G$${last},"Cash advance"`)},{value:s.fromAdvance,formula:sum(`,Transaksi!$J$7:$J$${last},"Cash advance"`)},{value:s.fromOffice,formula:sum(`,Transaksi!$J$7:$J$${last},"Kantor"`)},{value:s.balance,formula:`C${r}-E${r}-F${r}`},{value:s.pending,formula:sum(`,Transaksi!$I$7:$I$${last},"Belum dibayar"`)},{value:s.after,formula:`H${r}-I${r}`}];});
const s=summary(t);const totalRow:Cell[]=['TOTAL','',...[s.advance,s.expense,s.direct,s.fromAdvance,s.fromOffice,s.balance,s.pending,s.after].map((v,i)=>({value:v,formula:`SUM(${col(i+2)}7:${col(i+2)}${6+scopes.length})`}))];
const tx:Cell[][]=t.transactions.map(x=>['Day '+x.day,dayDate(t,x.day),x.description,x.vendor||'-',x.category,method(x),source(x),x.amount,status(x),paidFrom(x),x.settledAt?stamp(x.settledAt):'-',x.note||'-',x.receipts.length]);
const receipts:Cell[][]=t.transactions.flatMap(x=>x.receipts.map(r=>['Day '+x.day,x.description,r.name,{text:'Buka struk',url:link(r.id,origin)}]));
const logs:Cell[][]=audit.filter(a=>a.tripId===t.id).map(a=>[stamp(a.at),a.actor,a.action,auditDetail(a.detail)]);
const sheets=[
{title:'Laporan cash advance',note:'Satu baris per CA harian/gabungan; CA bersama dihitung sekali. Rincian per hari ada di Transaksi.',headers:['Hari','Tanggal','Cash advance','Pengeluaran','Langsung dari CA','Reimburse dari CA','Reimburse kantor','Sisa aktual','Belum reimburse','Sisa proyeksi'],widths:[12,19,22,22,22,22,22,22,22,22],rows:daily,numbers:[2,3,4,5,6,7,8,9],total:totalRow},
{title:'Rincian transaksi',note:'Reimburse adalah pelunasan uang pribadi, bukan pengeluaran baru.',headers:['Hari','Tanggal','Keperluan','Nama','Kategori','Metode','Sumber dana','Nominal','Status reimburse','Pelunasan dari','Tanggal pelunasan','Catatan','Jumlah struk'],widths:[12,19,40,28,22,18,22,22,22,22,26,45,15],rows:tx,numbers:[7]},
{title:'Daftar struk pembayaran',note:'Klik Buka struk. Akses situs diperlukan untuk melihat lampiran.',headers:['Hari','Keperluan','Nama file','Lampiran'],widths:[12,45,55,20],rows:receipts,numbers:[]},
{title:'Riwayat perubahan',note:'Waktu dicatat dalam WITA. Rincian memperlihatkan perubahan sebelum dan sesudah.',headers:['Waktu (WITA)','Anggota','Tindakan','Rincian perubahan'],widths:[28,35,30,110],rows:logs,numbers:[]}
];
sheets.forEach((sh,idx)=>{const end=col(sh.headers.length-1);const rows=sh.rows.length?sh.rows:[['Belum ada data',...Array(sh.headers.length-1).fill('')]];const hyperlinks:string[]=[],rels:string[]=[];
const cell=(v:Cell,r:number,c:number,st:string)=>{const ref=col(c)+r;if(typeof v==='object'&&'url'in v){const id='rId'+(rels.length+1);rels.push(`<Relationship Id="${id}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="${xml(v.url)}" TargetMode="External"/>`);hyperlinks.push(`<hyperlink ref="${ref}" r:id="${id}"/>`);return `<c r="${ref}" s="${hyper}" t="inlineStr"><is><t>${xml(v.text)}</t></is></c>`;}if(typeof v==='object')return `<c r="${ref}" s="${st}"><f>${xml(v.formula)}</f><v>${v.value}</v></c>`;if(typeof v==='number')return `<c r="${ref}" s="${st}"><v>${v}</v></c>`;return `<c r="${ref}" s="${st}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`;};
const row=(r:number,values:Cell[],st:string,height:number)=>`<row r="${r}" ht="${height}" customHeight="1">${values.map((v,c)=>cell(v,r,c,st)).join('')}</row>`;
let data=row(2,[sh.title+' | '+t.name],title,30)+row(3,[dayDate(t,1)+' - '+dayDate(t,t.days)+' | '+t.days+' hari | Rupiah (IDR)'],subtitle,23)+row(4,[sh.note],subtitle,25)+row(6,sh.headers,header,36);
rows.forEach((values,i)=>{const r=i+7;const wrapped=Math.max(...values.map((v,c)=>typeof v==='string'?v.split('\n').reduce((a,l)=>a+Math.max(1,Math.ceil(l.length/(sh.widths[c]*.9))),0):1));const height=Math.min(400,Math.max(30,wrapped*15+12));data+=`<row r="${r}" ht="${height}" customHeight="1">${values.map((v,c)=>cell(v,r,c,sh.numbers.includes(c)?(i%2?moneyBand:money):v==='Belum dibayar'?pending:i%2?band:body)).join('')}</row>`;});
if(sh.total){const r=7+rows.length;data+=`<row r="${r}" ht="32" customHeight="1">${sh.total.map((v,c)=>cell(v,r,c,c>=2?totalMoney:total)).join('')}</row>`;}
zip[`xl/worksheets/sheet${idx+1}.xml`]=strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetPr><tabColor rgb="FF174F46"/><pageSetUpPr fitToPage="1"/></sheetPr><dimension ref="A1:${end}${6+rows.length+(sh.total?1:0)}"/><sheetViews><sheetView showGridLines="0" workbookViewId="0"><pane xSplit="1" ySplit="6" topLeftCell="B7" activePane="bottomRight" state="frozen"/><selection pane="bottomRight" activeCell="B7" sqref="B7"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="22"/><cols>${sh.widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')}</cols><sheetData>${data}</sheetData><autoFilter ref="A6:${end}${6+rows.length}"/><mergeCells count="3"><mergeCell ref="A2:${end}2"/><mergeCell ref="A3:${end}3"/><mergeCell ref="A4:${end}4"/></mergeCells>${hyperlinks.length?'<hyperlinks>'+hyperlinks.join('')+'</hyperlinks>':''}<pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup paperSize="9" orientation="landscape" fitToWidth="1" fitToHeight="0"/><headerFooter><oddFooter>&amp;L Tour Ledger &amp;R Halaman &amp;P / &amp;N</oddFooter></headerFooter></worksheet>`);
if(rels.length)zip[`xl/worksheets/_rels/sheet${idx+1}.xml.rels`]=strToU8(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${rels.join('')}</Relationships>`);
});
zip['xl/workbook.xml']=strToU8(strFromU8(zip['xl/workbook.xml']).replace(/<(?:x:)?calcPr\b[^>]*\/>/g,'').replace('</x:workbook>','<x:calcPr calcId="191029" fullCalcOnLoad="1"/></x:workbook>'));return zipSync(zip,{level:6});
}
export async function createPdf(t:Trip,origin:string){
const {jsPDF}=await import('jspdf');const {autoTable}=await import('jspdf-autotable');const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});const W=297,H=210,M=16,GREEN='#174F46';
const clean=(s:string)=>s.replace(/[\u2013\u2014]/g,'-');
function heading(section:string){doc.setFillColor(GREEN);doc.rect(0,0,W,3,'F');doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(GREEN);doc.text('TOUR LEDGER',M,14);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor('#708078');doc.text(section,W-M,14,{align:'right'});doc.setFont('helvetica','bold');doc.setFontSize(18);doc.setTextColor('#203F35');const lines=doc.splitTextToSize(clean(t.name),W-M*2);doc.text(lines,M,26);const y=26+lines.length*7;doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor('#6B7E73');doc.text(`${dayDate(t,1)} - ${dayDate(t,t.days)} | ${t.days} hari | IDR / Rupiah`,M,y);return y+8;}
function cards(y:number,items:[string,number][]){const cw=(W-M*2-15)/4;items.forEach(([label,value],i)=>{const x=M+i*(cw+5);doc.setFillColor(i===0?GREEN:'#F0F5F2');doc.roundedRect(x,y,cw,24,2,2,'F');doc.setTextColor(i===0?'#D4E6DB':'#6B7E73');doc.setFontSize(9);doc.text(label,x+5,y+7);doc.setFont('helvetica','bold');doc.setFontSize(14);doc.setTextColor(value<0?'#B53A36':i===0?'#E2F6A0':'#234A39');doc.text(rupiah(value),x+5,y+17);doc.setFont('helvetica','normal');});return y+32;}
const base:any={theme:'plain',margin:{left:M,right:M,top:43,bottom:17},styles:{font:'helvetica',fontSize:9,cellPadding:3,textColor:'#294238',lineColor:'#DFE8E1',lineWidth:{bottom:.15},overflow:'linebreak',valign:'top'},headStyles:{fillColor:GREEN,textColor:'#FFFFFF',fontStyle:'bold',fontSize:8.5,halign:'left'},alternateRowStyles:{fillColor:'#F1F5F2'},footStyles:{fillColor:'#DEEAE1',textColor:GREEN,fontStyle:'bold'},rowPageBreak:'avoid',showHead:'everyPage',showFoot:'lastPage'};
let pageStart=1;let section='LAPORAN CASH ADVANCE';const continuation=()=>{if(doc.getCurrentPageInfo().pageNumber>pageStart)heading(section+' - LANJUTAN')};
const total=summary(t);let y=heading(section);y=cards(y,[['Total cash advance',total.advance],['Total pengeluaran',total.expense],['Sisa aktual',total.balance],['Belum direimburse',total.pending]]);
autoTable(doc,{...base,startY:y,head:[['Hari / tanggal','Cash advance','Pengeluaran','Reimburse CA','Dari kantor','Sisa aktual','Belum reimburse']],body:budgetScopes(t).map(g=>{const s=budgetSummary(t,g.start);return [budgetLabel(t,g.start)+'\n'+dayDate(t,g.start)+(g.end!==g.start?' - '+dayDate(t,g.end):''),rupiah(s.advance),rupiah(s.expense),rupiah(s.fromAdvance),rupiah(s.fromOffice),rupiah(s.balance),rupiah(s.pending)]}),foot:[['TOTAL',rupiah(total.advance),rupiah(total.expense),rupiah(total.fromAdvance),rupiah(total.fromOffice),rupiah(total.balance),rupiah(total.pending)]],columnStyles:{0:{cellWidth:37},1:{halign:'right'},2:{halign:'right'},3:{halign:'right'},4:{halign:'right'},5:{halign:'right'},6:{halign:'right'}},didDrawPage:continuation});
function note(s:string){let y=(doc as any).lastAutoTable.finalY+8;if(y+Math.ceil(s.length/155)*4>H-18){doc.addPage();y=heading('CATATAN REKONSILIASI');}doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor('#5C7063');doc.text(doc.splitTextToSize(s,W-M*2),M,y);}
note(`Jika seluruh reimburse tertunda dilunasi dari CA, sisa dana: ${rupiah(total.after)}. Nilai negatif berarti kekurangan dana. CA gabungan dihitung sekali per kelompok hari; CA lainnya tetap terpisah. Reimburse tidak dihitung sebagai biaya baru.`);
for(let day=1;day<=t.days;day++){doc.addPage();pageStart=doc.getCurrentPageInfo().pageNumber;section=`DAY ${String(day).padStart(2,'0')} / ${dayDate(t,day)}`;const s=summary(t,day),budget=budgetSummary(t,day),label=budgetLabel(t,day);y=heading(section);y=cards(y,[['CA '+clean(label),budget.advance],['Pengeluaran hari ini',s.expense],['Sisa CA '+clean(label),budget.balance],['Belum reimburse hari ini',s.pending]]);const tx=t.transactions.filter(x=>x.day===day);
autoTable(doc,{...base,startY:y,head:[['No.','Keperluan / Nama','Pembayaran','Nominal','Reimburse','Catatan / struk']],body:tx.length?tx.map((x,i)=>[String(i+1),clean(x.description)+'\n'+clean(x.vendor||'-')+'\n'+clean(x.category),method(x)+'\n'+source(x),rupiah(x.amount),status(x)+(x.settled?'\nDari '+paidFrom(x)+(x.settledAt?'\n'+stamp(x.settledAt):''):''),clean(x.note||'-')+'\n'+(x.receipts.length?x.receipts.length+' struk (lihat lampiran)':'Belum ada struk')]):[['-','Belum ada transaksi','','','','']],columnStyles:{0:{cellWidth:12},1:{cellWidth:65},2:{cellWidth:35},3:{cellWidth:36,halign:'right'},4:{cellWidth:45},5:{cellWidth:72}},foot:[['','TOTAL PENGELUARAN','',rupiah(s.expense),'','']],didDrawPage:continuation});
note(`Rekonsiliasi ${clean(label)}${groupFor(t,day)?' (saldo bersama seluruh kelompok, bukan saldo harian)':''}: CA ${rupiah(budget.advance)} - pengeluaran langsung ${rupiah(budget.direct)} - reimburse dari CA ${rupiah(budget.fromAdvance)} = sisa aktual ${rupiah(budget.balance)}. Sisa setelah seluruh reimburse kelompok dibayar dari CA: ${rupiah(budget.after)}.`);}
const receipts=t.transactions.flatMap(x=>x.receipts.map(r=>({day:x.day,description:x.description,...r})));if(receipts.length){doc.addPage();pageStart=doc.getCurrentPageInfo().pageNumber;section='LAMPIRAN STRUK';y=heading(section);autoTable(doc,{...base,startY:y,head:[['Hari','Keperluan','Nama struk','Tautan']],body:receipts.map(r=>['Day '+r.day,clean(r.description),clean(r.name),'Buka struk']),columnStyles:{0:{cellWidth:20},1:{cellWidth:85},2:{cellWidth:125},3:{cellWidth:35,textColor:'#176E81'}},didDrawPage:continuation,didDrawCell:(data:any)=>{if(data.section==='body'&&data.column.index===3)doc.link(data.cell.x,data.cell.y,data.cell.width,data.cell.height,{url:link(receipts[data.row.index].id,origin)})}});}
const pages=doc.getNumberOfPages();for(let p=1;p<=pages;p++){doc.setPage(p);doc.setDrawColor('#D9E3DB');doc.line(M,H-13,W-M,H-13);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor('#728177');doc.text('Tour Ledger | Laporan keuangan perjalanan | Tautan struk memerlukan akses situs',M,H-8);doc.text(`${p} / ${pages}`,W-M,H-8,{align:'right'});}return doc;
}
export async function exportTrip(t:Trip,audit:Audit[],kind:'xlsx'|'pdf'){
const filename=(t.name.replace(/[^a-zA-Z0-9_-]/g,'_')||'Trip')+'_Laporan';if(kind==='pdf'){(await createPdf(t,location.origin)).save(filename+'.pdf');return;}
const r=await fetch('/report-template.xlsx');if(!r.ok)throw Error('Template laporan tidak tersedia');const bytes=await createWorkbook(t,audit,location.origin,new Uint8Array(await r.arrayBuffer()));const url=URL.createObjectURL(new Blob([bytes as BlobPart],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download=filename+'.xlsx';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);
}
