import {getChatGPTUser} from '@/app/chatgpt-auth';
import {admin} from '@/lib/supabase';
import {receiptById} from '@/lib/storage';
import {sameOrigin} from '@/lib/request-security';
import {MAX_RECEIPT_SIZE,RECEIPT_TYPES,validReceipt} from '@/lib/receipt-validation';
export const dynamic='force-dynamic';
export async function POST(req:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Masuk diperlukan.'},{status:401});if(!sameOrigin(req))return Response.json({error:'Ditolak.'},{status:403});try{const b=await req.json();const c=admin();const bucket=c.storage.from('receipts');
if(b.action==='prepare'){if(typeof b.name!=='string'||!b.name.trim()||b.name.length>180||!Number.isSafeInteger(b.size)||b.size<1||b.size>MAX_RECEIPT_SIZE||!RECEIPT_TYPES.includes(b.type))throw Error('Gunakan JPG, PNG, WebP, atau PDF hingga 10 MB.');const id=crypto.randomUUID();const {error}=await c.from('receipts').insert({id,name:b.name,type:b.type,size:b.size,actor:user.email,ready:false});if(error)throw error;const {data,error:signError}=await bucket.createSignedUploadUrl(id);if(signError||!data)throw signError||Error('Unggah belum tersedia.');return Response.json({id,token:data.token,path:data.path},{headers:{'Cache-Control':'no-store'}});}
if(b.action==='complete'){if(typeof b.id!=='string'||!/^[a-f0-9-]{36}$/.test(b.id))throw Error('Struk tidak valid.');const {data:row,error}=await c.from('receipts').select('*').eq('id',b.id).eq('actor',user.email).maybeSingle();if(error||!row)throw Error('Struk tidak ditemukan.');if(row.ready)return Response.json({id:row.id,name:row.name});const {data:file,error:downloadError}=await bucket.download(row.id);if(downloadError||!file)throw Error('Unggahan belum selesai.');if(file.size!==row.size||!validReceipt(new Uint8Array(await file.arrayBuffer()),row.type)){await bucket.remove([row.id]);await c.from('receipts').delete().eq('id',row.id);throw Error('Isi file tidak sesuai format atau ukuran.');}const {error:saveError}=await c.from('receipts').update({ready:true}).eq('id',row.id);if(saveError)throw saveError;return Response.json({id:row.id,name:row.name});}
throw Error('Tindakan tidak valid.');}catch(e){console.error('Receipt upload failed',e);return Response.json({error:e instanceof Error?e.message:'Unggah gagal. Coba lagi.'},{status:400});}}
export async function GET(req:Request){if(!await getChatGPTUser())return new Response('Masuk diperlukan',{status:401});try{const id=new URL(req.url).searchParams.get('id');if(!id)return new Response('Tidak ditemukan',{status:404});const r=await receiptById(id);if(!r)return new Response('Tidak ditemukan',{status:404});const {data,error}=await admin().storage.from('receipts').createSignedUrl(id,60,{download:r.name});if(error||!data)throw error;return new Response(null,{status:302,headers:{Location:data.signedUrl,'Cache-Control':'private, no-store','Referrer-Policy':'no-referrer'}});}catch{return new Response('Struk belum bisa dimuat',{status:503});}}
